### ISSUE TITLE
Does not support Chinese clients

### ISSUE THREAD

**Issue by WZHER** [TacticalDeuce/circuit-watcher#1]
Your small software is very simple, I like it very much, but it is a pity that it does not support Chinese clients. (Google Translate)

**Comment by TacticalDeux** [comment]
Huh that's weird, unless you mean it doesn't support Chinese character (which at the moment I'm not planning to implement), in theory it should support any client since all the program really does is POST and GET requests to the LCU api endpoints. Could you check if this program works for you and if it does can you send me the value you get from doing a get request to lol-gameflow-session inside a lobby on your league client? https://github.com/HextechDocs/lcu-explorer/releases.
The response should look something like:
```js
{
  "gameClient": {
    "observerServerIp": "string",
    "observerServerPort": 0,
    "running": true,
    "serverIp": "string",
    "serverPort": 0,
    "visible": true
  },
  "gameData": {
    "gameId": 0,
    "gameName": "string",
    "isCustomGame": true,
    "password": "string",
    "playerChampionSelections": [
      {
        "additionalProp1": {}
      }
    ],
    "queue": {
      "allowablePremadeSizes": [
        0
      ],
      "areFreeChampionsAllowed": true,
      "assetMutator": "string",
      "category": "None",
      "championsRequiredToPlay": 0,
      "description": "string",
      "detailedDescription": "string",
      "gameMode": "string",
      "gameTypeConfig": {
        "advancedLearningQuests": true,
        "allowTrades": true,
        "banMode": "string",
        "banTimerDuration": 0,
        "battleBoost": true,
        "crossTeamChampionPool": true,
        "deathMatch": true,
        "doNotRemove": true,
        "duplicatePick": true,
        "exclusivePick": true,
        "id": 0,
        "learningQuests": true,
        "mainPickTimerDuration": 0,
        "maxAllowableBans": 0,
        "name": "string",
        "onboardCoopBeginner": true,
        "pickMode": "string",
        "postPickTimerDuration": 0,
        "reroll": true,
        "teamChampionPool": true
      },
      "id": 0,
      "isRanked": true,
      "isTeamBuilderManaged": true,
      "isTeamOnly": true,
      "lastToggledOffTime": 0,
      "lastToggledOnTime": 0,
      "mapId": 0,
      "maxLevel": 0,
      "maxSummonerLevelForFirstWinOfTheDay": 0,
      "maximumParticipantListSize": 0,
      "minLevel": 0,
      "minimumParticipantListSize": 0,
      "name": "string",
      "numPlayersPerTeam": 0,
      "queueAvailability": "Available",
      "queueRewards": {
        "isChampionPointsEnabled": true,
        "isIpEnabled": true,
        "isXpEnabled": true,
        "partySizeIpRewards": [
          0
        ]
      },
      "removalFromGameAllowed": true,
      "removalFromGameDelayMinutes": 0,
      "shortName": "string",
      "showPositionSelector": true,
      "spectatorEnabled": true,
      "type": "string"
    },
    "spectatorsAllowed": true,
    "teamOne": [
      {
        "additionalProp1": {}
      }
    ],
    "teamTwo": [
      {
        "additionalProp1": {}
      }
    ]
  },
  "gameDodge": {
    "dodgeIds": [
      0
    ],
    "phase": "None",
    "state": "Invalid"
  },
  "map": {
    "assets": {
      "additionalProp1": {}
    },
    "categorizedContentBundles": {
      "additionalProp1": {}
    },
    "description": "string",
    "gameMode": "string",
    "gameModeName": "string",
    "gameModeShortName": "string",
    "gameMutator": "string",
    "id": 0,
    "isRGM": true,
    "mapStringId": "string",
    "name": "string",
    "perPositionDisallowedSummonerSpells": {
      "additionalProp1": {
        "spells": [
          0
        ]
      },
      "additionalProp2": {
        "spells": [
          0
        ]
      },
      "additionalProp3": {
        "spells": [
          0
        ]
      }
    },
    "perPositionRequiredSummonerSpells": {
      "additionalProp1": {
        "spells": [
          0
        ]
      },
      "additionalProp2": {
        "spells": [
          0
        ]
      },
      "additionalProp3": {
        "spells": [
          0
        ]
      }
    },
    "platformId": "string",
    "platformName": "string",
    "properties": {
      "additionalProp1": {}
    }
  },
  "phase": "None"
}
```

Step-by-step on how to get the GET request value:
![image](https://github.com/TacticalDeuce/circuit-watcher/assets/66234915/ea92515e-9ea0-4b82-9eea-4012740c5f88)
![image](https://github.com/TacticalDeuce/circuit-watcher/assets/66234915/93f34538-b5fc-447c-a0e9-4da3eb35f2c3)
![image](https://github.com/TacticalDeuce/circuit-watcher/assets/66234915/0f66febd-7858-4252-bcf6-6a388f8b0232)
![image](https://github.com/TacticalDeuce/circuit-watcher/assets/66234915/5770aae5-023d-4790-b885-6f0be0a8b079)
![image](https://github.com/TacticalDeuce/circuit-watcher/assets/66234915/d6a678a8-b753-4fd0-bbfa-0e99a2752660)

**Comment by WZHER** [comment]
Thank you, I didn't expect you to reply me. It is reasonable to say that the Chinese client also supports API, because there are many software similar to querying records in the Chinese market (I don't like them because they will charge or have too many functions). But I don't know why your software can't run correctly, the following is my picture according to your operation (maybe there is something wrong with my operation, I'm a novice). I used to use python to auto-accept games based on image recognition, but it was so dumb, I ditched it XD.Don't have to spend too much energy here, hope it doesn't bother you.

`{
  "gameClient": {
    "observerServerIp": "string",
    "observerServerPort": 0,
    "running": true,
    "serverIp": "string",
    "serverPort": 0,
    "visible": true
  },
  "gameData": {
    "gameId": 0,
    "gameName": "string",
    "isCustomGame": true,
    "password": "string",
    "playerChampionSelections": [
      {
        "additionalProp1": {}
      }
    ],
    "queue": {
      "allowablePremadeSizes": [
        0
      ],
      "areFreeChampionsAllowed": true,
      "assetMutator": "string",
      "category": "None",
      "championsRequiredToPlay": 0,
      "description": "string",
      "detailedDescription": "string",
      "gameMode": "string",
      "gameTypeConfig": {
        "advancedLearningQuests": true,
        "allowTrades": true,
        "banMode": "string",
        "banTimerDuration": 0,
        "battleBoost": true,
        "crossTeamChampionPool": true,
        "deathMatch": true,
        "doNotRemove": true,
        "duplicatePick": true,
        "exclusivePick": true,
        "id": 0,
        "learningQuests": true,
        "mainPickTimerDuration": 0,
        "maxAllowableBans": 0,
        "name": "string",
        "onboardCoopBeginner": true,
        "pickMode": "string",
        "postPickTimerDuration": 0,
        "reroll": true,
        "teamChampionPool": true
      },
      "id": 0,
      "isRanked": true,
      "isTeamBuilderManaged": true,
      "isTeamOnly": true,
      "lastToggledOffTime": 0,
      "lastToggledOnTime": 0,
      "mapId": 0,
      "maxLevel": 0,
      "maxSummonerLevelForFirstWinOfTheDay": 0,
      "maximumParticipantListSize": 0,
      "minLevel": 0,
      "minimumParticipantListSize": 0,
      "name": "string",
      "numPlayersPerTeam": 0,
      "queueAvailability": "Available",
      "queueRewards": {
        "isChampionPointsEnabled": true,
        "isIpEnabled": true,
        "isXpEnabled": true,
        "partySizeIpRewards": [
          0
        ]
      },
      "removalFromGameAllowed": true,
      "removalFromGameDelayMinutes": 0,
      "shortName": "string",
      "showPositionSelector": true,
      "spectatorEnabled": true,
      "type": "string"
    },
    "spectatorsAllowed": true,
    "teamOne": [
      {
        "additionalProp1": {}
      }
    ],
    "teamTwo": [
      {
        "additionalProp1": {}
      }
    ]
  },
  "gameDodge": {
    "dodgeIds": [
      0
    ],
    "phase": "None",
    "state": "Invalid"
  },
  "map": {
    "assets": {
      "additionalProp1": {}
    },
    "categorizedContentBundles": {
      "additionalProp1": {}
    },
    "description": "string",
    "gameMode": "string",
    "gameModeName": "string",
    "gameModeShortName": "string",
    "gameMutator": "string",
    "id": 0,
    "isRGM": true,
    "mapStringId": "string",
    "name": "string",
    "perPositionDisallowedSummonerSpells": {
      "additionalProp1": {
        "spells": [
          0
        ]
      },
      "additionalProp2": {
        "spells": [
          0
        ]
      },
      "additionalProp3": {
        "spells": [
          0
        ]
      }
    },
    "perPositionRequiredSummonerSpells": {
      "additionalProp1": {
        "spells": [
          0
        ]
      },
      "additionalProp2": {
        "spells": [
          0
        ]
      },
      "additionalProp3": {
        "spells": [
          0
        ]
      }
    },
    "platformId": "string",
    "platformName": "string",
    "properties": {
      "additionalProp1": {}
    }
  },
  "phase": "None"
}`
![client](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/7c2ded78-937f-47d3-a693-3f42879face5)
![session](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/97f6e300-9f53-49b8-a34c-cf9b57884f4d)
![session_all](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/28537ba7-b455-4db5-a44c-93d974b65872)
![software](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/db79a57e-a80d-4155-98d8-3da76aadac61)

**Comment by TacticalDeux** [comment]
It seems that it's not about it not being able to do the requests but just straight up not connecting to the League Client, and the LCU explorer application doesn't seem to be connecting to your client either. If I had to guess it's either the data that needs to be extracted to make this requests is encode in variables named in Chinese (which I doubt but could be) or the LeagueClient process is in named in Chinese (which I also doubt), the only real option would be for you to go and check the contents of your lockfile, you can do that by going to your Riot Games installation folder (usually at C:\Riot Games) go into the League of Legends folder and check the file named "lockfile", it should have 5 values each separated by a colon like this `LeagueClient:12345:54321:password:https`, is the first value (LeagueClient) still in English? if so, are the folders (riot games and league of legend) in English? 
if everything is as it normally would on non-Chinese clients then I don't really know what's the problem, and if you ever find a solution or a different way to get the LeagueClient's port and auth token for Chinese clients I can try and implement it into my program and make a separate Chinese supporting release.

**Comment by WZHER** [comment]
As you said, the software is not connected to the client. I know why. I searched for information today (https://github.com/XHXIAIEIN/LeagueCustomLobby) and found that the official Chinese version has changed the way of lockfile, and it is currently impossible to find the key with the previous method. Now it needs to be found by reading the process data. Just like the picture, so you can get the port and auth token anyway. Enter "wmic PROCESS WHERE name='LeagueClientUx.exe' GET commandline" at the command prompt to get the JSON file, and then you can get the port and authentication token. Thank you, I use the website to directly enter https://127.0.0.1:<port>, and found that the account name is riot
![Snipaste_2023-07-20_21-41-36](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/8f2c1976-df25-4fba-bca4-90e2d8a72f2f)
![Snipaste_2023-07-20_21-41-54](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/09d59b9e-be3a-4d85-b5ae-b8077f6b6979)
![Snipaste_2023-07-20_21-42-03](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/30876229-7b52-4106-a11c-9f6a55f55112)
![QQ截图20230720215938](https://github.com/TacticalDeuce/circuit-watcher/assets/42331706/2db38375-6e8c-4970-9822-8471383d7302)

**Comment by TacticalDeux** [comment]
Okay so WMIC method does work which is really good. I'm going to try and fix this for next release, seems easy enough so I should be able to get it done by today or maybe tomorrow.

**Comment by TacticalDeux** [comment]
Should be fixed on the [latest release](https://github.com/TacticalDeuce/circuit-watcher/releases/tag/v2.3.7)
